version: '2'
services:

  mongodb:
    image: "mongo:latest@sha256:968de6d4e8d28de52158d7ff6744422bd94aedd375df4ea93617cd7491329850"
    container_name: mongodb
    environment:
      - DOCKER_LABELS=true
    ports:
      - "27017:27017"
    expose:
      - 27017

  rabbitmq:
    image: sammlerio/rabbitmq:latest@sha256:7a295c01e08647990a8037be06c8dbd21824e688cdd2f3c56ff0a12f7353bcbe
    container_name: rabbitmq
    ports:
      - "8080:15672"
      - "5672:5672"
    logging:
      driver: none

#  scheduler-service:
#    image: sammlerio/scheduler-service
#    container_name: scheduler-service
#    environment:
#      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672
#      - LOAD_JOBS_FROM_FILE=true
#    command: ["npm", "run", "start:watch"]
#    volumes:
#      - ./node_modules/scheduler-service:/opt/scheduler-service
#      - ./configs/scheduler-service/jobs:/opt/scheduler-service/src/config/jobs

